---
title: "historical-spx-constituents-data-for-free"
format: html
---

```{sql}

```
+ https://robotwealth.com/how-to-get-historical-spx-constituents-data-for-free/
+ https://github.com/Robot-Wealth/trader-tales/tree/master/historical-spx-constituents
+ https://github.com/leosmigel/analyzingalpha/tree/master
  S&P historical components
  https://en.wikipedia.org/wiki/List_of_S%26P_500_companies#S&P_500_component_stocks
  https://analyzingalpha.com/sp500-historical-components-and-changes
+ https://github.com/Robot-Wealth/trader-tales/blob/master/historical-spx-constituents/historical-spx-constituents.Rmd


```{r}
if (!require("pacman")) install.packages("pacman")
pacman::p_load(tidyverse, rvest)
wikispx <- read_html('https://en.wikipedia.org/wiki/List_of_S%26P_500_companies')
currentconstituents <- wikispx %>%
  html_node('#constituents') %>%
  html_table(header = TRUE)

# Scrape the current S&P 500 constituents
current_constituents <- wikispx %>%
    html_node("#constituents") %>%
    html_table(header = TRUE) |>
    janitor::clean_names() 
current_constituents |> 
    glimpse()

spxchanges <- wikispx %>%
  html_node('#changes') %>%
  html_table(header = FALSE, fill = TRUE) %>%
  filter(row_number() > 2) %>% # First two rows are headers
  `colnames<-`(c('Date','AddTicker','AddName','RemovedTicker','RemovedName','Reason')) %>%
  mutate(Date = as.Date(Date, format = '%B %d, %Y'),
         year = year(Date),
         month = month(Date))
spxchanges |> glimpse()
```


```{r}
# Start at the current constituents...
currentmonth <- as.Date(format(Sys.Date(), '%Y-%m-01'))
monthseq <- seq.Date(as.Date('1990-01-01'), currentmonth, by = 'month') %>% rev()

spxstocks <- currentconstituents %>% 
    mutate(Date = currentmonth) %>% 
    select(Date, Ticker = Symbol, Name = Security)
lastrunstocks <- spxstocks

# Iterate through months, working backwards
for (i in 2:length(monthseq)) {
  d <- monthseq[i]
  y <- year(d)
  m <- month(d)
  changes <- spxchanges %>% 
    filter(year == year(d), month == month(d)) 

  # Remove added tickers (we're working backwards in time, remember)
  tickerstokeep <- lastrunstocks %>% 
    anti_join(changes, by = c('Ticker' = 'AddTicker')) %>%
    mutate(Date = d)
  
  # Add back the removed tickers...
  tickerstoadd <- changes %>%
    filter(!RemovedTicker == '') %>%
        transmute(Date = d,
                  Ticker = RemovedTicker,
                  Name = RemovedName)
  
  thismonth <- tickerstokeep %>% bind_rows(tickerstoadd)
  spxstocks <- spxstocks %>% bind_rows(thismonth)  
  
  lastrunstocks <- thismonth
}
spxstocks


# spxchanges |> 
#     mutate(across(where(~ !inherits(., "Date")), 
#         ~ type.convert(., as.is = TRUE))) |> 
#     janitor::clean_names() ->
#     spxchanges
# spxchanges |>
#    glimpse()



```
